"""PACT concern catalog for AVDM concern evaluation."""
from __future__ import annotations


PACT_LAYERS = [
    "Business / Organization",
    "Context & Application",
    "Container / Component / Technical Service",
    "Integration & Processing",
    "Data Architecture",
    "Security, Compliance & Risk",
    "Architecture Governance & Decision",
    "Deployment / Infrastructure / Networking",
    "Operations & Reliability",
]


def _concern(
    key: str,
    name: str,
    layer: str,
    primary_concern: str,
    question: str,
    stakeholders: list[str],
    focus: str,
    scope: str,
    risk_tags: list[str],
) -> dict[str, object]:
    return {
        "key": key,
        "name": name,
        "layer": layer,
        "primary_concern": primary_concern,
        "key_question": question,
        "stakeholders": stakeholders,
        "focus": focus,
        "scope": scope,
        "risk_tags": [key, *risk_tags],
        "description": f"{primary_concern}. {question}",
    }


CONCERN_CATALOG: list[dict[str, object]] = [
    _concern("B1", "Business Capability View", "Business / Organization", "Capability structure", "What business capabilities exist and which are critical?", ["Executives", "EA"], "Structural", "Logical", ["business", "capability", "scope"]),
    _concern("B2", "Business Process View", "Business / Organization", "End-to-end workflows", "How do business processes execute across domains?", ["Product", "Operations"], "Behavioral", "Logical", ["business", "process", "workflow"]),
    _concern("B3", "User / Actor View", "Business / Organization", "Users and roles", "Who interacts with the system and in what roles?", ["Product", "Security"], "Structural", "Logical", ["user", "role", "identity"]),
    _concern("B4", "Organizational Ownership View", "Business / Organization", "Accountability and governance", "Who owns systems, data, and decisions?", ["Executives", "EA"], "Structural", "Logical", ["ownership", "governance", "accountability"]),
    _concern("B5", "Interaction & Influence View", "Business / Organization", "Cross-domain influence", "How do organizational units influence each other?", ["Product", "Architecture"], "Structural", "Logical", ["business", "organization", "dependency"]),
    _concern("A1", "System Context View", "Context & Application", "System boundary", "What is inside and outside the system?", ["Product", "Development"], "Structural", "Logical", ["application", "context", "boundary"]),
    _concern("A2", "Application Functional View", "Context & Application", "Functional decomposition", "How are application functions grouped?", ["Product", "Development"], "Structural", "Logical", ["application", "function", "decomposition"]),
    _concern("A3", "Application Interaction View", "Context & Application", "Application collaboration", "How do applications interact and depend on each other?", ["Development", "Integration"], "Behavioral", "Logical", ["application", "integration", "dependency"]),
    _concern("A4", "User Role-Application Mapping View", "Context & Application", "Access responsibility", "Which roles can access which applications?", ["Product", "Security"], "Structural / Behavioral", "Logical", ["authorization", "role", "application"]),
    _concern("C1", "Container View", "Container / Component / Technical Service", "Runtime containers", "What are the main runtime units?", ["Solution Architects", "Development"], "Structural", "Logical", ["container", "runtime", "application"]),
    _concern("C2", "Component View", "Container / Component / Technical Service", "Internal modularity", "How are components structured within containers?", ["Solution Architects", "Development"], "Structural", "Logical", ["component", "modularity", "refactor"]),
    _concern("C3", "Technical Service View", "Container / Component / Technical Service", "Service responsibility", "What capability boundary does each service own?", ["Development", "Architects"], "Structural", "Logical", ["service", "ownership", "boundary"]),
    _concern("C4", "Technical Stack View", "Container / Component / Technical Service", "Technology choices", "Which languages, frameworks, and platforms are used?", ["Development", "Operations"], "Structural", "Physical", ["technology", "platform", "standard"]),
    _concern("C5", "Communication & Protocol View", "Container / Component / Technical Service", "Interaction mechanisms", "How do components communicate?", ["Development", "SRE"], "Structural / Behavioral", "Logical / Physical", ["protocol", "communication", "network"]),
    _concern("IP1", "Application Integration View", "Integration & Processing", "Business-level integration", "How do applications exchange data?", ["Product", "Integration"], "Behavioral", "Logical", ["integration", "data", "application"]),
    _concern("IP2", "Technical Integration View", "Integration & Processing", "Technical constraints", "What latency, throughput, or coupling constraints exist?", ["Development", "SRE"], "Behavioral", "Physical", ["integration", "performance", "coupling"]),
    _concern("IP3", "System Processing View", "Integration & Processing", "Execution semantics", "How are requests processed end-to-end?", ["Development", "Operations"], "Behavioral", "Logical", ["processing", "runtime", "workflow"]),
    _concern("IP4", "Activity View", "Integration & Processing", "Action paths", "What actions and decisions occur during execution?", ["Architects", "Development"], "Behavioral", "Logical", ["activity", "decision", "workflow"]),
    _concern("IP5", "Process Flow View", "Integration & Processing", "Workflow execution", "How do workflows orchestrate services?", ["Product", "SRE"], "Behavioral", "Logical", ["process", "orchestration", "workflow"]),
    _concern("IP6", "Sequence Interaction View", "Integration & Processing", "Call ordering", "What is the interaction sequence?", ["Development", "Architects"], "Behavioral", "Logical", ["sequence", "interaction", "integration"]),
    _concern("D1", "Business Data Flow View", "Data Architecture", "Business data movement", "How does data support business processes?", ["Product", "Operations"], "Behavioral", "Logical", ["data", "flow", "business"]),
    _concern("D2", "Data Derivation & Evolution View", "Data Architecture", "Data transformation", "How is data derived and transformed?", ["Data Engineering", "ML"], "Behavioral", "Logical / Physical", ["data", "transformation", "ai"]),
    _concern("D3", "Data Lineage View", "Data Architecture", "Traceability", "Where does data originate and propagate?", ["Compliance", "Data Engineering"], "Behavioral", "Logical / Physical", ["data", "lineage", "traceability"]),
    _concern("D4", "Data Asset View", "Data Architecture", "Ownership and value", "What data assets exist and who owns them?", ["Data Office"], "Structural", "Physical", ["data", "asset", "ownership"]),
    _concern("D5", "Conceptual Data Entity View", "Data Architecture", "Business entities", "What core business entities exist?", ["Data Architects", "Business"], "Structural", "Logical", ["data", "entity", "model"]),
    _concern("D6", "Data Quality View", "Data Architecture", "Quality assurance", "Is data accurate, complete, and timely?", ["Data Stewards"], "Structural / Behavioral", "Logical / Physical", ["data", "quality", "governance"]),
    _concern("D7", "Data Compliance Flow View", "Data Architecture", "Regulatory paths", "Does data usage comply with regulations?", ["Compliance", "Product"], "Behavioral", "Logical / Physical", ["data", "compliance", "privacy"]),
    _concern("D8", "Data Pipeline View", "Data Architecture", "Technical pipelines", "How is data processed technically?", ["Data Engineering"], "Behavioral", "Physical", ["data", "pipeline", "ai"]),
    _concern("D9", "Data Sovereignty View", "Data Architecture", "Residency constraints", "Where is data stored and restricted?", ["Compliance", "EA"], "Structural", "Physical", ["data", "sovereignty", "residency"]),
    _concern("D10", "Logical Data Model View", "Data Architecture", "Logical schema", "How are entities logically related?", ["Development", "Data Architects"], "Structural", "Logical", ["data", "logical_model", "entity"]),
    _concern("D11", "Physical Data Model View", "Data Architecture", "Physical schema", "How is data physically implemented?", ["DBA", "Development"], "Structural", "Physical", ["data", "physical_model", "database"]),
    _concern("SCR1", "Security Control View", "Security, Compliance & Risk", "Control mechanisms", "What controls enforce security policy?", ["Security", "DevOps"], "Structural / Behavioral", "Logical / Physical", ["security", "control", "policy"]),
    _concern("SCR2", "Threat & Risk Modeling View", "Security, Compliance & Risk", "Threat analysis", "What threats and risks exist?", ["Security", "Risk"], "Structural / Behavioral", "Logical / Physical", ["security", "risk", "threat"]),
    _concern("SCR3", "Attack Path View", "Security, Compliance & Risk", "Adversarial traversal", "How could an attacker move through the system?", ["Security", "Incident Response"], "Behavioral", "Physical", ["security", "attack", "network"]),
    _concern("SCR4", "Service Authentication View", "Security, Compliance & Risk", "Service trust", "How do services authenticate each other?", ["Security", "Development"], "Structural / Behavioral", "Logical / Physical", ["security", "service_auth", "identity"]),
    _concern("SCR5", "User Authentication View", "Security, Compliance & Risk", "User identity", "How are users authenticated?", ["Security", "Product"], "Structural / Behavioral", "Logical / Physical", ["security", "user_auth", "identity"]),
    _concern("SCR6", "Authorization & Access Control View", "Security, Compliance & Risk", "Access enforcement", "Who is authorized to do what?", ["Security", "Compliance"], "Structural / Behavioral", "Logical", ["security", "authorization", "access"]),
    _concern("SCR7", "Compliance Boundary View", "Security, Compliance & Risk", "Regulatory scope", "Which regulations apply and where?", ["Compliance", "EA"], "Structural", "Logical / Physical", ["compliance", "regulatory", "boundary"]),
    _concern("AGD1", "Architecture Decision View", "Architecture Governance & Decision", "Decision rationale", "What architectural decisions were made and why?", ["Architects", "EA"], "Structural", "Logical", ["governance", "decision", "rationale"]),
    _concern("AGD2", "Evolution & Change Impact View", "Architecture Governance & Decision", "Change analysis", "What is impacted by a proposed change?", ["Architects", "Product"], "Behavioral", "Logical", ["governance", "change", "impact"]),
    _concern("AGD3", "Quality Attribute Trade-off View", "Architecture Governance & Decision", "Trade-off reasoning", "How are quality attributes balanced?", ["Architects", "SRE"], "Structural / Behavioral", "Logical", ["governance", "quality", "risk"]),
    _concern("AGD4", "Cost & Value View", "Architecture Governance & Decision", "Economic impact", "What are the costs and expected value?", ["Executives", "Finance"], "Structural", "Logical", ["governance", "cost", "value"]),
    _concern("AGD5", "Team-Architecture Alignment View", "Architecture Governance & Decision", "Organizational fit", "Are teams aligned with the architecture?", ["Engineering Managers"], "Structural", "Logical", ["governance", "team", "ownership"]),
    _concern("DIN1", "Application Deployment Location View", "Deployment / Infrastructure / Networking", "Deployment topology", "Where are applications deployed?", ["EA", "Infrastructure"], "Structural", "Physical", ["deployment", "location", "infrastructure"]),
    _concern("DIN2", "Network Topology View", "Deployment / Infrastructure / Networking", "Network segmentation", "How is the network structured?", ["Network", "Security"], "Structural", "Physical", ["network", "segmentation", "security"]),
    _concern("DIN3", "Infrastructure Composition View", "Deployment / Infrastructure / Networking", "Infrastructure layout", "What infrastructure components exist?", ["Development", "Operations"], "Structural", "Physical", ["infrastructure", "platform", "deployment"]),
    _concern("DIN4", "Resource & Capacity View", "Deployment / Infrastructure / Networking", "Scaling and capacity", "How are resources allocated and scaled?", ["SRE", "Infrastructure"], "Structural", "Physical", ["capacity", "scalability", "performance"]),
    _concern("OR1", "Operations View", "Operations & Reliability", "Incident handling", "How are incidents managed operationally?", ["Operations", "Development"], "Behavioral", "Physical", ["operations", "incident", "runbook"]),
    _concern("OR2", "Resilience & DR View", "Operations & Reliability", "Recovery strategy", "What are RPO/RTO objectives?", ["Infrastructure", "Executives"], "Structural / Behavioral", "Physical", ["resilience", "recovery", "continuity"]),
    _concern("OR3", "Reliability & SLO View", "Operations & Reliability", "Reliability targets", "What service levels are required?", ["Development", "SRE"], "Structural / Behavioral", "Logical", ["reliability", "slo", "availability"]),
    _concern("OR4", "Monitoring & Observability View", "Operations & Reliability", "System visibility", "How is system health observed?", ["Development", "SRE"], "Structural", "Logical", ["observability", "monitoring", "operations"]),
    _concern("OR5", "Operational Feedback View", "Operations & Reliability", "Learning loops", "How do operations inform evolution?", ["Architects", "Operations"], "Behavioral", "Logical", ["operations", "feedback", "evolution"]),
]
